# Generated by Django 4.2.8 on 2023-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_project_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/imgs'),
        ),
    ]
